pki:
  ca: /etc/snc/ca.crt
  cert: /etc/snc/host.crt
  key: /etc/snc/host.key

static_host_map:
  "172.52.0.1": ["0.0.0.0:4242"]

lighthouse:
  am_lighthouse: true
  interval: 60

listen:
  host: 0.0.0.0
  port: 4242
  read_buffer: 10485760
  write_buffer: 10485760

punchy:
  punch: true

tun:
  dev: snc2
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
    - mtu: 1300
      route: 172.52.0.1/8
      via: 172.52.0.1

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      groups:
        - mgmt

    - port: 22
      proto: tcp
      groups:
        - ssh

